#!/usr/bin/python3
from sig_helper import get_quote

lines = [
    ('Jonathan Sumner Evans', 'Graduate Student, Computer Science'),
    ('https://sumnerevans.com', 'Chair, Mines ACM'),
    ('+1 (720) 459-1501', 'Service Chair, TBP'),
    ('GPG: B50022FD', 'Linux Help Guru, LUG'),
]

print('\n'.join('{:32}{}'.format(*x) for x in lines))
print()
print(get_quote())
