#!/usr/bin/python3
from sig_helper import get_quote, print_contact_info

titles = [
    ('Vice President', 'Mines Student ACM Chapter'),
    ('Secretary', 'Mines Linux Users Group (LUG)'),
    ('Teachers Assistant', 'Data Structures'),
]

print('Jonathan Sumner Evans')
print('Colorado School of Mines')
print('B.S. Computer Science')
for title in titles:
    print('{0}, {1}'.format(*title))
print_contact_info('jonathanevans@mines.edu')
print(get_quote())
